version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.19.1
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
      - ./config:/vault/config
      - ./certs:/vault/certs
    command: "vault server -config=/vault/config/vault.hcl"
    environment:
      VAULT_ADDR: "https://0.0.0.0:8200"
volumes:
  vault-data:
